### ISSUE TITLE
Settings: Disable "Hot Corner" trigger, as it can cause multiple seconds slowdown like when watching a video or such

### ISSUE THREAD

**Issue by star-buck** [blue-systems/neon-pinebook#57]

**Comment by subdiff** [comment]
The reason why it's slow is because we force compositing to Xrender and not use Gl compositing. The reason for this again was that we had graphical glitches somewhere in the graphics stack when doing Gl accelerated compositing.

As long as we force Xrender it makes therefore sense to deactivate the hot corner as default.

But the correct fix in the long run must be to use a clean Gl accelerated graphic stack.

**Comment by star-buck** [comment]
I agree with long term.
Using hotcorners default, especially this one, is generally debatable though, in terms of people wishing for more commonly defaults.

**Comment by bhush9** [comment]
The fix was packaged, but I am not sure if it made in http://weegie.edinburghlinux.co.uk/~neon/images/pinebook-remix/20180209-1549/ or not.. most likely it was included, if not please revert Ready for QA back

**Comment by star-buck** [comment]
done
