### ISSUE TITLE
datetime: ff: seems some https issue due to too long ago date

### ISSUE THREAD

**Issue by star-buck** [blue-systems/neon-pinebook#89]
![screenshot_20180128_171623](https://user-images.githubusercontent.com/840070/43710672-8d929a42-9970-11e8-9fb8-20bacdc41ed0.png)

**Comment by bhush9** [comment]
This looks like is due to date configuration being wrong?

**Comment by bhush9** [comment]
for record,

```
14:49 <bshah> well this time bug fix is breaking working clock for me :/ my hardware RTC clock is set to correct time, I add service which sets the time to build timestamp, at boot, time is updated from time server, after that service triggers setting time in past
14:49 <bshah> which is completely broken behavior
14:49 <bshah> and also for some reason, after setting time to correct time "once" timesyncd never catces up
```

I am investigating more.

**Comment by bhush9** [comment]
Found issue. Trying potential fix locally.

**Comment by bhush9** [comment]
The issue we thought was missing libnss-systemd which was removed to fix the #77 but it doesn't seem to have helped with the problem.

**Comment by star-buck** [comment]
Yeah, its still 1:30-2 minutes before live boots up here.

**Comment by bhush9** [comment]
Um no, That delay bug is already fixed

it takes roughly 1:30-2 minutes to boot sure, but not 1:30-2 minutes of blocking (and total of 4 minutes of boot time), what I meant was fix for the delay bug might have caused this bug of time, but that was not cause.

**Comment by star-buck** [comment]
i think it is 1:30-2min of blocked boot time, right after the neon logo disappears

then it takes that time before cursor shows up and the splash comes... then it takes again some 1:00min to boot from splash into full desktop appears

will test with next new flashed img and stopwatch time in new ticket.

**Comment by bhush9** [comment]
So I have image which supposedly should fix wrong date and time,

# Testing done

- Since my hardware clock was already in correct form I set it to Sept 13 2010, it doesn't allow me to set anything less then 2010 for some reason (probably good reason I believe)
- Shutdown and reboot into the mate image to ensure that hardware clock and system clock state is "wrong" (as-in it stores Sept 13 2010 date), don't connect to internet as otherwise time would sync automatically from internet. Shutdown pinebook completely and reboot twice to ensure that something didn't "fix" the date to proper date.
- Download image from : https://files.kde.org/neon/images/pinebook-remix-nonfree/useredition/20180807-1615/ and flash it to SD card
- Boot the image, without connecting internet.
- Date is set to the Jan 28, which is still wrong and should be set to 7 August 2018, I am not sure from where Jan 28 comes from.
- Connect internet
- Load github.com, which loads fine.
- ntp kicks in and sets correct date, which is August 8.

In general there is something still wrong but I am out of time unfortunately today and tomorrow is travel time., so this will have to wait till Akademy or after Akademy. If anyone have free time and wants to figure this out, help would be appreciated.

**Comment by adriaandegroot** [comment]
> - Connect internet
> - Load github.com, which loads fine.

This will fail when the certificate start date is in the future -- that's a problem I have fairly regularly in VMs which have been suspended for a while and where sync-to-host-clock is disabled (e.g. whatever a default Manjaro install does). For instance, when I set the date (manually) to january 28th and try github from my local VM, I get a "not secure" notice from FF, telling me the date on my computer is probably wrong.

**Comment by bhush9** [comment]
Okay finally I figured out what was issue with build_stamp workaround, I was using timedatectl, but since timesyncd is not started at that point, it will fail/hang forever. I have fixed it to use the traditional date command.

https://files.kde.org/neon/images/pinebook-remix-nonfree/useredition/20180808-1033/

# Testing done:

- From mate image set time to something in past (2012-12-12 in this case of testing)
- Sync time with hwclock (`sudo hwclock --systohc`)
- This puts system in broken time state where time is not correct and SSL certificates are invalid
- Reboot twice to ensure hwclock is still on old time (`sudo hwclock --get`)
- Flash image `20180808-1033` which have `/.disk/build_stamp` of the `2018-08-08 11:02:35`
- Boot image
- Date is now `2018-08-08 11:02:xx`
- Connect internet
- Check https website and see it works
- NTP kicks in and sets correct time
- Install

# Boot delay

I checked this with timer, and it seems that the delay was due to wrong time only, now fixing it i get desktop in 1 minute 21 seconds.. Which is quite reasonable.

**Comment by davidedmundson** [comment]
I tried with one MicroSD card and had a failed boot. This card was weirdly hot after writing it, so probably doesn't count but worth mentioning.

Next boot with a new card and a different usb writer:
Boot took 1 minute 41
Timestamp on boot was 8th August 11am
After connecting to the internet NTP did not update immediately
NTP did update after a few minutes.

**Comment by star-buck** [comment]
is this satisfyingly fixed to not block RC release?

**Comment by star-buck** [comment]
closing for now
